// Supabase project configuration

const SUPABASE_URL = "https://dbvaitlmfxqhhobsofdj.supabase.co";

const SUPABASE_ANON_KEY =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidmFpdGxtZnhxaGhvYnNvZmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDY5ODAsImV4cCI6MjA4NzQyMjk4MH0.icPnH8xKg3Nz1WxSY0pjtsSFZIuLzqboQ62fJDh0hzg";
